// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dagryn/cluster/v1/cluster.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkerHeartbeat is sent periodically by the worker agent.
type WorkerHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Info          *WorkerInfo            `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`           // Sent on first heartbeat only
	Resources     *ResourceSnapshot      `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"` // Sent on every heartbeat
	ActiveTasks   int32                  `protobuf:"varint,4,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHeartbeat) Reset() {
	*x = WorkerHeartbeat{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHeartbeat) ProtoMessage() {}

func (x *WorkerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHeartbeat.ProtoReflect.Descriptor instead.
func (*WorkerHeartbeat) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerHeartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHeartbeat) GetInfo() *WorkerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *WorkerHeartbeat) GetResources() *ResourceSnapshot {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *WorkerHeartbeat) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *WorkerHeartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// WorkerInfo describes a worker agent's capabilities and environment.
type WorkerInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Hostname           string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os                 string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch               string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Environment        string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"` // "kubernetes", "docker", "bare-metal"
	Labels             map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MaxConcurrentTasks int32                  `protobuf:"varint,6,opt,name=max_concurrent_tasks,json=maxConcurrentTasks,proto3" json:"max_concurrent_tasks,omitempty"`
	Capabilities       []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // "docker", "gpu", "arm64", etc.
	Version            string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`           // Agent version for compat checks
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *WorkerInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *WorkerInfo) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *WorkerInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *WorkerInfo) GetMaxConcurrentTasks() int32 {
	if x != nil {
		return x.MaxConcurrentTasks
	}
	return 0
}

func (x *WorkerInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *WorkerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ResourceSnapshot is a point-in-time snapshot of worker resources.
type ResourceSnapshot struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CpuMillicoresAvailable int64                  `protobuf:"varint,1,opt,name=cpu_millicores_available,json=cpuMillicoresAvailable,proto3" json:"cpu_millicores_available,omitempty"`
	MemoryBytesAvailable   int64                  `protobuf:"varint,2,opt,name=memory_bytes_available,json=memoryBytesAvailable,proto3" json:"memory_bytes_available,omitempty"`
	DiskBytesAvailable     int64                  `protobuf:"varint,3,opt,name=disk_bytes_available,json=diskBytesAvailable,proto3" json:"disk_bytes_available,omitempty"`
	CpuUsagePercent        float64                `protobuf:"fixed64,4,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsagePercent     float64                `protobuf:"fixed64,5,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResourceSnapshot) Reset() {
	*x = ResourceSnapshot{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSnapshot) ProtoMessage() {}

func (x *ResourceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSnapshot.ProtoReflect.Descriptor instead.
func (*ResourceSnapshot) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceSnapshot) GetCpuMillicoresAvailable() int64 {
	if x != nil {
		return x.CpuMillicoresAvailable
	}
	return 0
}

func (x *ResourceSnapshot) GetMemoryBytesAvailable() int64 {
	if x != nil {
		return x.MemoryBytesAvailable
	}
	return 0
}

func (x *ResourceSnapshot) GetDiskBytesAvailable() int64 {
	if x != nil {
		return x.DiskBytesAvailable
	}
	return 0
}

func (x *ResourceSnapshot) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *ResourceSnapshot) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

// ControlMessage is sent from the control plane to a worker.
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ControlMessage_Ack
	//	*ControlMessage_Drain
	//	*ControlMessage_Shutdown
	Message       isControlMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *ControlMessage) GetMessage() isControlMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ControlMessage) GetAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ControlMessage) GetDrain() *DrainRequest {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *ControlMessage) GetShutdown() *ShutdownRequest {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isControlMessage_Message interface {
	isControlMessage_Message()
}

type ControlMessage_Ack struct {
	Ack *HeartbeatAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type ControlMessage_Drain struct {
	Drain *DrainRequest `protobuf:"bytes,2,opt,name=drain,proto3,oneof"`
}

type ControlMessage_Shutdown struct {
	Shutdown *ShutdownRequest `protobuf:"bytes,3,opt,name=shutdown,proto3,oneof"`
}

func (*ControlMessage_Ack) isControlMessage_Message() {}

func (*ControlMessage_Drain) isControlMessage_Message() {}

func (*ControlMessage_Shutdown) isControlMessage_Message() {}

// HeartbeatAck acknowledges a worker heartbeat.
type HeartbeatAck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerTime        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	HeartbeatInterval *durationpb.Duration   `protobuf:"bytes,2,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	WorkerId          string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // Assigned on first heartbeat (registration)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatAck) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *HeartbeatAck) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

func (x *HeartbeatAck) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// DrainRequest asks the worker to stop accepting new tasks.
type DrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	GracePeriod   *durationpb.Duration   `protobuf:"bytes,2,opt,name=grace_period,json=gracePeriod,proto3" json:"grace_period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *DrainRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DrainRequest) GetGracePeriod() *durationpb.Duration {
	if x != nil {
		return x.GracePeriod
	}
	return nil
}

// ShutdownRequest asks the worker to shut down.
type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *ShutdownRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// TaskAssignment is sent from the control plane to a worker to execute a task.
type TaskAssignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId   string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	RunId          string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TaskName       string                 `protobuf:"bytes,4,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Command        string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	Workdir        string                 `protobuf:"bytes,6,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Env            map[string]string      `protobuf:"bytes,7,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutMs      int64                  `protobuf:"varint,8,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Container      *ContainerConfig       `protobuf:"bytes,9,opt,name=container,proto3" json:"container,omitempty"`
	InputPatterns  []string               `protobuf:"bytes,10,rep,name=input_patterns,json=inputPatterns,proto3" json:"input_patterns,omitempty"`
	OutputPatterns []string               `protobuf:"bytes,11,rep,name=output_patterns,json=outputPatterns,proto3" json:"output_patterns,omitempty"`
	// Source code delivery
	//
	// Types that are valid to be assigned to Source:
	//
	//	*TaskAssignment_Git
	//	*TaskAssignment_Artifact
	Source        isTaskAssignment_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *TaskAssignment) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *TaskAssignment) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TaskAssignment) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *TaskAssignment) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskAssignment) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TaskAssignment) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *TaskAssignment) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *TaskAssignment) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *TaskAssignment) GetContainer() *ContainerConfig {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *TaskAssignment) GetInputPatterns() []string {
	if x != nil {
		return x.InputPatterns
	}
	return nil
}

func (x *TaskAssignment) GetOutputPatterns() []string {
	if x != nil {
		return x.OutputPatterns
	}
	return nil
}

func (x *TaskAssignment) GetSource() isTaskAssignment_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TaskAssignment) GetGit() *GitSource {
	if x != nil {
		if x, ok := x.Source.(*TaskAssignment_Git); ok {
			return x.Git
		}
	}
	return nil
}

func (x *TaskAssignment) GetArtifact() *ArtifactSource {
	if x != nil {
		if x, ok := x.Source.(*TaskAssignment_Artifact); ok {
			return x.Artifact
		}
	}
	return nil
}

type isTaskAssignment_Source interface {
	isTaskAssignment_Source()
}

type TaskAssignment_Git struct {
	Git *GitSource `protobuf:"bytes,20,opt,name=git,proto3,oneof"`
}

type TaskAssignment_Artifact struct {
	Artifact *ArtifactSource `protobuf:"bytes,21,opt,name=artifact,proto3,oneof"`
}

func (*TaskAssignment_Git) isTaskAssignment_Source() {}

func (*TaskAssignment_Artifact) isTaskAssignment_Source() {}

// GitSource tells the worker how to clone the source code.
type GitSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Commit        string                 `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"` // Ephemeral clone token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitSource) Reset() {
	*x = GitSource{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitSource) ProtoMessage() {}

func (x *GitSource) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitSource.ProtoReflect.Descriptor instead.
func (*GitSource) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *GitSource) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *GitSource) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GitSource) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GitSource) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ArtifactSource provides a pre-signed URL to a workspace tarball.
type ArtifactSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedUrl     string                 `protobuf:"bytes,1,opt,name=signed_url,json=signedUrl,proto3" json:"signed_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactSource) Reset() {
	*x = ArtifactSource{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactSource) ProtoMessage() {}

func (x *ArtifactSource) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactSource.ProtoReflect.Descriptor instead.
func (*ArtifactSource) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *ArtifactSource) GetSignedUrl() string {
	if x != nil {
		return x.SignedUrl
	}
	return ""
}

// ContainerConfig specifies container execution settings.
type ContainerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	MemoryLimit   string                 `protobuf:"bytes,2,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	CpuLimit      string                 `protobuf:"bytes,3,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	Network       string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerConfig) Reset() {
	*x = ContainerConfig{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfig) ProtoMessage() {}

func (x *ContainerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerConfig.ProtoReflect.Descriptor instead.
func (*ContainerConfig) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *ContainerConfig) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerConfig) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

func (x *ContainerConfig) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *ContainerConfig) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

// TaskEvent is sent from a worker back to the control plane.
type TaskEvent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	WorkerId     string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*TaskEvent_Accepted
	//	*TaskEvent_Rejected
	//	*TaskEvent_Result
	Event         isTaskEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *TaskEvent) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *TaskEvent) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskEvent) GetEvent() isTaskEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TaskEvent) GetAccepted() *TaskAccepted {
	if x != nil {
		if x, ok := x.Event.(*TaskEvent_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *TaskEvent) GetRejected() *TaskRejected {
	if x != nil {
		if x, ok := x.Event.(*TaskEvent_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *TaskEvent) GetResult() *TaskResult {
	if x != nil {
		if x, ok := x.Event.(*TaskEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isTaskEvent_Event interface {
	isTaskEvent_Event()
}

type TaskEvent_Accepted struct {
	Accepted *TaskAccepted `protobuf:"bytes,3,opt,name=accepted,proto3,oneof"`
}

type TaskEvent_Rejected struct {
	Rejected *TaskRejected `protobuf:"bytes,4,opt,name=rejected,proto3,oneof"`
}

type TaskEvent_Result struct {
	Result *TaskResult `protobuf:"bytes,5,opt,name=result,proto3,oneof"`
}

func (*TaskEvent_Accepted) isTaskEvent_Event() {}

func (*TaskEvent_Rejected) isTaskEvent_Event() {}

func (*TaskEvent_Result) isTaskEvent_Event() {}

// TaskAccepted indicates the worker has accepted the task assignment.
type TaskAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAccepted) Reset() {
	*x = TaskAccepted{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAccepted) ProtoMessage() {}

func (x *TaskAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAccepted.ProtoReflect.Descriptor instead.
func (*TaskAccepted) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{12}
}

// TaskRejected indicates the worker has rejected the task assignment.
type TaskRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRejected) Reset() {
	*x = TaskRejected{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRejected) ProtoMessage() {}

func (x *TaskRejected) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRejected.ProtoReflect.Descriptor instead.
func (*TaskRejected) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *TaskRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// TaskResult contains the outcome of a task execution.
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // Maps to executor.Status
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // String, not Go error (fix #2 from review: serializable)
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *TaskResult) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TaskResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TaskResult) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// LogEntry is a single log line streamed from a worker.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskName      string                 `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Stream        string                 `protobuf:"bytes,4,opt,name=stream,proto3" json:"stream,omitempty"` // "stdout" or "stderr"
	Line          string                 `protobuf:"bytes,5,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RunId         string                 `protobuf:"bytes,7,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // Run ID for SSE log routing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *LogEntry) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *LogEntry) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *LogEntry) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *LogEntry) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// LogAck acknowledges receipt of log entries.
type LogAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinesReceived int64                  `protobuf:"varint,1,opt,name=lines_received,json=linesReceived,proto3" json:"lines_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAck) Reset() {
	*x = LogAck{}
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAck) ProtoMessage() {}

func (x *LogAck) ProtoReflect() protoreflect.Message {
	mi := &file_dagryn_cluster_v1_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAck.ProtoReflect.Descriptor instead.
func (*LogAck) Descriptor() ([]byte, []int) {
	return file_dagryn_cluster_v1_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *LogAck) GetLinesReceived() int64 {
	if x != nil {
		return x.LinesReceived
	}
	return 0
}

var File_dagryn_cluster_v1_cluster_proto protoreflect.FileDescriptor

const file_dagryn_cluster_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1fdagryn/cluster/v1/cluster.proto\x12\x11dagryn.cluster.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x81\x02\n" +
	"\x0fWorkerHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x121\n" +
	"\x04info\x18\x02 \x01(\v2\x1d.dagryn.cluster.v1.WorkerInfoR\x04info\x12A\n" +
	"\tresources\x18\x03 \x01(\v2#.dagryn.cluster.v1.ResourceSnapshotR\tresources\x12!\n" +
	"\factive_tasks\x18\x04 \x01(\x05R\vactiveTasks\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xdc\x02\n" +
	"\n" +
	"WorkerInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12A\n" +
	"\x06labels\x18\x05 \x03(\v2).dagryn.cluster.v1.WorkerInfo.LabelsEntryR\x06labels\x120\n" +
	"\x14max_concurrent_tasks\x18\x06 \x01(\x05R\x12maxConcurrentTasks\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x02\n" +
	"\x10ResourceSnapshot\x128\n" +
	"\x18cpu_millicores_available\x18\x01 \x01(\x03R\x16cpuMillicoresAvailable\x124\n" +
	"\x16memory_bytes_available\x18\x02 \x01(\x03R\x14memoryBytesAvailable\x120\n" +
	"\x14disk_bytes_available\x18\x03 \x01(\x03R\x12diskBytesAvailable\x12*\n" +
	"\x11cpu_usage_percent\x18\x04 \x01(\x01R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\x05 \x01(\x01R\x12memoryUsagePercent\"\xcb\x01\n" +
	"\x0eControlMessage\x123\n" +
	"\x03ack\x18\x01 \x01(\v2\x1f.dagryn.cluster.v1.HeartbeatAckH\x00R\x03ack\x127\n" +
	"\x05drain\x18\x02 \x01(\v2\x1f.dagryn.cluster.v1.DrainRequestH\x00R\x05drain\x12@\n" +
	"\bshutdown\x18\x03 \x01(\v2\".dagryn.cluster.v1.ShutdownRequestH\x00R\bshutdownB\t\n" +
	"\amessage\"\xb2\x01\n" +
	"\fHeartbeatAck\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12H\n" +
	"\x12heartbeat_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\"d\n" +
	"\fDrainRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12<\n" +
	"\fgrace_period\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vgracePeriod\")\n" +
	"\x0fShutdownRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xe0\x04\n" +
	"\x0eTaskAssignment\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x1b\n" +
	"\ttask_name\x18\x04 \x01(\tR\btaskName\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x18\n" +
	"\aworkdir\x18\x06 \x01(\tR\aworkdir\x12<\n" +
	"\x03env\x18\a \x03(\v2*.dagryn.cluster.v1.TaskAssignment.EnvEntryR\x03env\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\b \x01(\x03R\ttimeoutMs\x12@\n" +
	"\tcontainer\x18\t \x01(\v2\".dagryn.cluster.v1.ContainerConfigR\tcontainer\x12%\n" +
	"\x0einput_patterns\x18\n" +
	" \x03(\tR\rinputPatterns\x12'\n" +
	"\x0foutput_patterns\x18\v \x03(\tR\x0eoutputPatterns\x120\n" +
	"\x03git\x18\x14 \x01(\v2\x1c.dagryn.cluster.v1.GitSourceH\x00R\x03git\x12?\n" +
	"\bartifact\x18\x15 \x01(\v2!.dagryn.cluster.v1.ArtifactSourceH\x00R\bartifact\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06source\"f\n" +
	"\tGitSource\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\tR\x06commit\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"/\n" +
	"\x0eArtifactSource\x12\x1d\n" +
	"\n" +
	"signed_url\x18\x01 \x01(\tR\tsignedUrl\"\x81\x01\n" +
	"\x0fContainerConfig\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12!\n" +
	"\fmemory_limit\x18\x02 \x01(\tR\vmemoryLimit\x12\x1b\n" +
	"\tcpu_limit\x18\x03 \x01(\tR\bcpuLimit\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\"\x8d\x02\n" +
	"\tTaskEvent\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12=\n" +
	"\baccepted\x18\x03 \x01(\v2\x1f.dagryn.cluster.v1.TaskAcceptedH\x00R\baccepted\x12=\n" +
	"\brejected\x18\x04 \x01(\v2\x1f.dagryn.cluster.v1.TaskRejectedH\x00R\brejected\x127\n" +
	"\x06result\x18\x05 \x01(\v2\x1d.dagryn.cluster.v1.TaskResultH\x00R\x06resultB\a\n" +
	"\x05event\"\x0e\n" +
	"\fTaskAccepted\"&\n" +
	"\fTaskRejected\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xae\x02\n" +
	"\n" +
	"TaskResult\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xe6\x01\n" +
	"\bLogEntry\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1b\n" +
	"\ttask_name\x18\x03 \x01(\tR\btaskName\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\tR\x06stream\x12\x12\n" +
	"\x04line\x18\x05 \x01(\tR\x04line\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x15\n" +
	"\x06run_id\x18\a \x01(\tR\x05runId\"/\n" +
	"\x06LogAck\x12%\n" +
	"\x0elines_received\x18\x01 \x01(\x03R\rlinesReceived2\x88\x02\n" +
	"\x0eClusterService\x12[\n" +
	"\x0eRegisterWorker\x12\".dagryn.cluster.v1.WorkerHeartbeat\x1a!.dagryn.cluster.v1.ControlMessage(\x010\x01\x12Q\n" +
	"\n" +
	"TaskStream\x12\x1c.dagryn.cluster.v1.TaskEvent\x1a!.dagryn.cluster.v1.TaskAssignment(\x010\x01\x12F\n" +
	"\n" +
	"StreamLogs\x12\x1b.dagryn.cluster.v1.LogEntry\x1a\x19.dagryn.cluster.v1.LogAck(\x01B+Z)github.com/mujhtech/dagryn/pkg/cluster/v1b\x06proto3"

var (
	file_dagryn_cluster_v1_cluster_proto_rawDescOnce sync.Once
	file_dagryn_cluster_v1_cluster_proto_rawDescData []byte
)

func file_dagryn_cluster_v1_cluster_proto_rawDescGZIP() []byte {
	file_dagryn_cluster_v1_cluster_proto_rawDescOnce.Do(func() {
		file_dagryn_cluster_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dagryn_cluster_v1_cluster_proto_rawDesc), len(file_dagryn_cluster_v1_cluster_proto_rawDesc)))
	})
	return file_dagryn_cluster_v1_cluster_proto_rawDescData
}

var file_dagryn_cluster_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_dagryn_cluster_v1_cluster_proto_goTypes = []any{
	(*WorkerHeartbeat)(nil),       // 0: dagryn.cluster.v1.WorkerHeartbeat
	(*WorkerInfo)(nil),            // 1: dagryn.cluster.v1.WorkerInfo
	(*ResourceSnapshot)(nil),      // 2: dagryn.cluster.v1.ResourceSnapshot
	(*ControlMessage)(nil),        // 3: dagryn.cluster.v1.ControlMessage
	(*HeartbeatAck)(nil),          // 4: dagryn.cluster.v1.HeartbeatAck
	(*DrainRequest)(nil),          // 5: dagryn.cluster.v1.DrainRequest
	(*ShutdownRequest)(nil),       // 6: dagryn.cluster.v1.ShutdownRequest
	(*TaskAssignment)(nil),        // 7: dagryn.cluster.v1.TaskAssignment
	(*GitSource)(nil),             // 8: dagryn.cluster.v1.GitSource
	(*ArtifactSource)(nil),        // 9: dagryn.cluster.v1.ArtifactSource
	(*ContainerConfig)(nil),       // 10: dagryn.cluster.v1.ContainerConfig
	(*TaskEvent)(nil),             // 11: dagryn.cluster.v1.TaskEvent
	(*TaskAccepted)(nil),          // 12: dagryn.cluster.v1.TaskAccepted
	(*TaskRejected)(nil),          // 13: dagryn.cluster.v1.TaskRejected
	(*TaskResult)(nil),            // 14: dagryn.cluster.v1.TaskResult
	(*LogEntry)(nil),              // 15: dagryn.cluster.v1.LogEntry
	(*LogAck)(nil),                // 16: dagryn.cluster.v1.LogAck
	nil,                           // 17: dagryn.cluster.v1.WorkerInfo.LabelsEntry
	nil,                           // 18: dagryn.cluster.v1.TaskAssignment.EnvEntry
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 20: google.protobuf.Duration
}
var file_dagryn_cluster_v1_cluster_proto_depIdxs = []int32{
	1,  // 0: dagryn.cluster.v1.WorkerHeartbeat.info:type_name -> dagryn.cluster.v1.WorkerInfo
	2,  // 1: dagryn.cluster.v1.WorkerHeartbeat.resources:type_name -> dagryn.cluster.v1.ResourceSnapshot
	19, // 2: dagryn.cluster.v1.WorkerHeartbeat.timestamp:type_name -> google.protobuf.Timestamp
	17, // 3: dagryn.cluster.v1.WorkerInfo.labels:type_name -> dagryn.cluster.v1.WorkerInfo.LabelsEntry
	4,  // 4: dagryn.cluster.v1.ControlMessage.ack:type_name -> dagryn.cluster.v1.HeartbeatAck
	5,  // 5: dagryn.cluster.v1.ControlMessage.drain:type_name -> dagryn.cluster.v1.DrainRequest
	6,  // 6: dagryn.cluster.v1.ControlMessage.shutdown:type_name -> dagryn.cluster.v1.ShutdownRequest
	19, // 7: dagryn.cluster.v1.HeartbeatAck.server_time:type_name -> google.protobuf.Timestamp
	20, // 8: dagryn.cluster.v1.HeartbeatAck.heartbeat_interval:type_name -> google.protobuf.Duration
	20, // 9: dagryn.cluster.v1.DrainRequest.grace_period:type_name -> google.protobuf.Duration
	18, // 10: dagryn.cluster.v1.TaskAssignment.env:type_name -> dagryn.cluster.v1.TaskAssignment.EnvEntry
	10, // 11: dagryn.cluster.v1.TaskAssignment.container:type_name -> dagryn.cluster.v1.ContainerConfig
	8,  // 12: dagryn.cluster.v1.TaskAssignment.git:type_name -> dagryn.cluster.v1.GitSource
	9,  // 13: dagryn.cluster.v1.TaskAssignment.artifact:type_name -> dagryn.cluster.v1.ArtifactSource
	12, // 14: dagryn.cluster.v1.TaskEvent.accepted:type_name -> dagryn.cluster.v1.TaskAccepted
	13, // 15: dagryn.cluster.v1.TaskEvent.rejected:type_name -> dagryn.cluster.v1.TaskRejected
	14, // 16: dagryn.cluster.v1.TaskEvent.result:type_name -> dagryn.cluster.v1.TaskResult
	19, // 17: dagryn.cluster.v1.TaskResult.start_time:type_name -> google.protobuf.Timestamp
	19, // 18: dagryn.cluster.v1.TaskResult.end_time:type_name -> google.protobuf.Timestamp
	19, // 19: dagryn.cluster.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 20: dagryn.cluster.v1.ClusterService.RegisterWorker:input_type -> dagryn.cluster.v1.WorkerHeartbeat
	11, // 21: dagryn.cluster.v1.ClusterService.TaskStream:input_type -> dagryn.cluster.v1.TaskEvent
	15, // 22: dagryn.cluster.v1.ClusterService.StreamLogs:input_type -> dagryn.cluster.v1.LogEntry
	3,  // 23: dagryn.cluster.v1.ClusterService.RegisterWorker:output_type -> dagryn.cluster.v1.ControlMessage
	7,  // 24: dagryn.cluster.v1.ClusterService.TaskStream:output_type -> dagryn.cluster.v1.TaskAssignment
	16, // 25: dagryn.cluster.v1.ClusterService.StreamLogs:output_type -> dagryn.cluster.v1.LogAck
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_dagryn_cluster_v1_cluster_proto_init() }
func file_dagryn_cluster_v1_cluster_proto_init() {
	if File_dagryn_cluster_v1_cluster_proto != nil {
		return
	}
	file_dagryn_cluster_v1_cluster_proto_msgTypes[3].OneofWrappers = []any{
		(*ControlMessage_Ack)(nil),
		(*ControlMessage_Drain)(nil),
		(*ControlMessage_Shutdown)(nil),
	}
	file_dagryn_cluster_v1_cluster_proto_msgTypes[7].OneofWrappers = []any{
		(*TaskAssignment_Git)(nil),
		(*TaskAssignment_Artifact)(nil),
	}
	file_dagryn_cluster_v1_cluster_proto_msgTypes[11].OneofWrappers = []any{
		(*TaskEvent_Accepted)(nil),
		(*TaskEvent_Rejected)(nil),
		(*TaskEvent_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dagryn_cluster_v1_cluster_proto_rawDesc), len(file_dagryn_cluster_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dagryn_cluster_v1_cluster_proto_goTypes,
		DependencyIndexes: file_dagryn_cluster_v1_cluster_proto_depIdxs,
		MessageInfos:      file_dagryn_cluster_v1_cluster_proto_msgTypes,
	}.Build()
	File_dagryn_cluster_v1_cluster_proto = out.File
	file_dagryn_cluster_v1_cluster_proto_goTypes = nil
	file_dagryn_cluster_v1_cluster_proto_depIdxs = nil
}
