import {
  HouseIcon,
  GearIcon,
  XIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  MonitorIcon,
  FolderIcon,
  ListBulletsIcon,
  UsersIcon,
  PlusIcon,
  CircleNotchIcon,
  GithubLogoIcon,
  DotsThreeVerticalIcon,
  DotsThreeOutlineIcon,
  SignOutIcon,
  EnvelopeIcon,
  CheckIcon,
  DatabaseIcon,
  PlayIcon,
  CircleIcon,
  CheckCircleIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitPullRequestIcon,
  NetworkIcon,
  CalendarIcon,
  XCircleIcon,
  ClockIcon,
  TrashIcon,
  UserMinusIcon,
  CopyIcon,
  KeyIcon,
  ChatCircleIcon,
  SidebarIcon,
  MagnifyingGlassIcon,
  LineSegmentsIcon,
  MinusIcon,
  FloppyDiskIcon,
  WifiSlashIcon,
  TerminalIcon,
  SquareIcon,
  DownloadIcon,
  BroadcastIcon,
  ChatTeardropDotsIcon,
  HardDriveIcon,
  TrendUpIcon,
  TrendDownIcon,
  TargetIcon,
  UploadIcon,
  UserIcon,
  WarningIcon,
  LinkIcon,
  LinkSimpleHorizontalIcon,
  PackageIcon,
  CreditCardIcon,
  LightbulbIcon,
  FileCodeIcon,
  ArrowClockwiseIcon,
  PaperPlaneTiltIcon,
  ShieldCheckIcon,
  CloudIcon,
  CubeIcon,
} from "@phosphor-icons/react";

export const Icons = {
  Home: HouseIcon,
  Settings: GearIcon,
  Close: XIcon,
  ArrowRight: ArrowRightIcon,
  ArrowLeft: ArrowLeftIcon,
  Dashboard: MonitorIcon,
  Folder: FolderIcon,
  ListDetails: ListBulletsIcon,
  Users: UsersIcon,
  Plus: PlusIcon,
  Loader: CircleNotchIcon,
  Github: GithubLogoIcon,
  DotsVertical: DotsThreeVerticalIcon,
  DotsHorizontal: DotsThreeOutlineIcon,
  Logout: SignOutIcon,
  Mail: EnvelopeIcon,
  Check: CheckIcon,
  Database: DatabaseIcon,
  Play: PlayIcon,
  Circle: CircleIcon,
  CheckCircle: CheckCircleIcon,
  ChevronLeft: ArrowLeftIcon,
  ChevronRight: ArrowRightIcon,
  ChevronUp: ArrowUpIcon,
  ChevronDown: ArrowDownIcon,
  GitBranch: GitBranchIcon,
  GitCommit: GitCommitIcon,
  GitPullRequest: GitPullRequestIcon,
  Network: NetworkIcon,
  Calendar: CalendarIcon,
  XCircle: XCircleIcon,
  Clock: ClockIcon,
  Trash: TrashIcon,
  UserMinus: UserMinusIcon,
  Copy: CopyIcon,
  Key: KeyIcon,
  ChatCircle: ChatCircleIcon,
  Sidebar: SidebarIcon,
  GripVertical: LineSegmentsIcon,
  Minus: MinusIcon,
  FloppyDisk: FloppyDiskIcon,
  WifiOff: WifiSlashIcon,
  Terminal: TerminalIcon,
  Square: SquareIcon,
  Download: DownloadIcon,
  Search: MagnifyingGlassIcon,
  BroadCast: BroadcastIcon,
  MessageCircle: ChatTeardropDotsIcon,
  HardDrive: HardDriveIcon,
  TrendUp: TrendUpIcon,
  TrendDown: TrendDownIcon,
  Upload: UploadIcon,
  Target: TargetIcon,
  User: UserIcon,
  Warning: WarningIcon,
  Link: LinkIcon,
  Link2: LinkSimpleHorizontalIcon,
  Package: PackageIcon,
  CreditCard: CreditCardIcon,
  Lightbulb: LightbulbIcon,
  FileCode: FileCodeIcon,
  Retry: ArrowClockwiseIcon,
  Send: PaperPlaneTiltIcon,
  ShieldCheck: ShieldCheckIcon,
  Cloud: CloudIcon,
  Box: CubeIcon,
  Monitor: MonitorIcon,
};
