/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as InvitationsIndexRouteImport } from './routes/invitations/index'
import { Route as AuthDeviceRouteImport } from './routes/auth/device'
import { Route as TeamsTeamIdIndexRouteImport } from './routes/teams/$teamId/index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdCacheRouteImport } from './routes/projects/$projectId/cache'
import { Route as AuthProviderCallbackRouteImport } from './routes/auth/$provider/callback'
import { Route as ProjectsProjectIdRunsRunIdRouteImport } from './routes/projects/$projectId/runs/$runId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsIndexRoute = InvitationsIndexRouteImport.update({
  id: '/invitations/',
  path: '/invitations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/auth/device',
  path: '/auth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdIndexRoute = TeamsTeamIdIndexRouteImport.update({
  id: '/teams/$teamId/',
  path: '/teams/$teamId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdCacheRoute = ProjectsProjectIdCacheRouteImport.update({
  id: '/projects/$projectId/cache',
  path: '/projects/$projectId/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProviderCallbackRoute = AuthProviderCallbackRouteImport.update({
  id: '/auth/$provider/callback',
  path: '/auth/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRunsRunIdRoute =
  ProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/projects/$projectId/runs/$runId',
    path: '/projects/$projectId/runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/auth/device': typeof AuthDeviceRoute
  '/invitations/': typeof InvitationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/projects/$projectId/cache': typeof ProjectsProjectIdCacheRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/auth/device': typeof AuthDeviceRoute
  '/invitations': typeof InvitationsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/projects/$projectId/cache': typeof ProjectsProjectIdCacheRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/auth/device': typeof AuthDeviceRoute
  '/invitations/': typeof InvitationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/projects/$projectId/cache': typeof ProjectsProjectIdCacheRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/auth/device'
    | '/invitations/'
    | '/projects/'
    | '/teams/'
    | '/auth/$provider/callback'
    | '/projects/$projectId/cache'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/teams/$teamId/'
    | '/projects/$projectId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/auth/device'
    | '/invitations'
    | '/projects'
    | '/teams'
    | '/auth/$provider/callback'
    | '/projects/$projectId/cache'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/teams/$teamId'
    | '/projects/$projectId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/auth/device'
    | '/invitations/'
    | '/projects/'
    | '/teams/'
    | '/auth/$provider/callback'
    | '/projects/$projectId/cache'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/teams/$teamId/'
    | '/projects/$projectId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AuthDeviceRoute: typeof AuthDeviceRoute
  InvitationsIndexRoute: typeof InvitationsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  AuthProviderCallbackRoute: typeof AuthProviderCallbackRoute
  ProjectsProjectIdCacheRoute: typeof ProjectsProjectIdCacheRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
  ProjectsProjectIdRunsRunIdRoute: typeof ProjectsProjectIdRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/': {
      id: '/invitations/'
      path: '/invitations'
      fullPath: '/invitations/'
      preLoaderRoute: typeof InvitationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/device': {
      id: '/auth/device'
      path: '/auth/device'
      fullPath: '/auth/device'
      preLoaderRoute: typeof AuthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof TeamsTeamIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/cache': {
      id: '/projects/$projectId/cache'
      path: '/projects/$projectId/cache'
      fullPath: '/projects/$projectId/cache'
      preLoaderRoute: typeof ProjectsProjectIdCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$provider/callback': {
      id: '/auth/$provider/callback'
      path: '/auth/$provider/callback'
      fullPath: '/auth/$provider/callback'
      preLoaderRoute: typeof AuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/runs/$runId': {
      id: '/projects/$projectId/runs/$runId'
      path: '/projects/$projectId/runs/$runId'
      fullPath: '/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof ProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AuthDeviceRoute: AuthDeviceRoute,
  InvitationsIndexRoute: InvitationsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  AuthProviderCallbackRoute: AuthProviderCallbackRoute,
  ProjectsProjectIdCacheRoute: ProjectsProjectIdCacheRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
  ProjectsProjectIdRunsRunIdRoute: ProjectsProjectIdRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
