/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Dashboard_layoutRouteImport } from './routes/_dashboard_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as AuthDeviceRouteImport } from './routes/auth/device'
import { Route as Dashboard_layoutSettingsRouteImport } from './routes/_dashboard_layout/settings'
import { Route as Dashboard_layoutLicenseRouteImport } from './routes/_dashboard_layout/license'
import { Route as Dashboard_layoutDashboardRouteImport } from './routes/_dashboard_layout/dashboard'
import { Route as Dashboard_layoutAnalyticsRouteImport } from './routes/_dashboard_layout/analytics'
import { Route as Dashboard_layoutTeamsIndexRouteImport } from './routes/_dashboard_layout/teams/index'
import { Route as Dashboard_layoutProjectsIndexRouteImport } from './routes/_dashboard_layout/projects/index'
import { Route as Dashboard_layoutInvitationsIndexRouteImport } from './routes/_dashboard_layout/invitations/index'
import { Route as Dashboard_layoutClustersIndexRouteImport } from './routes/_dashboard_layout/clusters/index'
import { Route as Dashboard_layoutPluginsIndexRouteImport } from './routes/_dashboard_layout/plugins/index'
import { Route as Dashboard_layoutPluginsPublishersIndexRouteImport } from './routes/_dashboard_layout/plugins/publishers/index'
import { Route as Dashboard_layoutWorkersIndexRouteImport } from './routes/_dashboard_layout/workers/index'
import { Route as Dashboard_layoutProjectsNewIndexRouteImport } from './routes/_dashboard_layout/projects/new/index'
import { Route as Dashboard_layoutProjectsProjectIdRunsIndexRouteImport } from './routes/_dashboard_layout/projects/$projectId/runs/index'
import { Route as AuthProviderCallbackRouteImport } from './routes/auth/$provider/callback'
import { Route as Dashboard_layoutWorkersWorkerIdRouteImport } from './routes/_dashboard_layout/workers/$workerId'
import { Route as Dashboard_layoutPluginsPublishRouteImport } from './routes/_dashboard_layout/plugins/publish'
import { Route as Dashboard_layoutPluginsBrowseRouteImport } from './routes/_dashboard_layout/plugins/browse'
import { Route as Dashboard_layoutPluginsPluginNameRouteImport } from './routes/_dashboard_layout/plugins/$pluginName'
import { Route as Dashboard_layoutClustersClusterIdRouteImport } from './routes/_dashboard_layout/clusters/$clusterId'
import { Route as Dashboard_layoutTeamsTeamIdIndexRouteImport } from './routes/_dashboard_layout/teams/$teamId/index'
import { Route as Dashboard_layoutProjectsProjectIdIndexRouteImport } from './routes/_dashboard_layout/projects/$projectId/index'
import { Route as Dashboard_layoutTeamsTeamIdSsoRouteImport } from './routes/_dashboard_layout/teams/$teamId/sso'
import { Route as Dashboard_layoutTeamsTeamIdAnalyticsRouteImport } from './routes/_dashboard_layout/teams/$teamId/analytics'
import { Route as Dashboard_layoutProjectsNewGithubRouteImport } from './routes/_dashboard_layout/projects/new/github'
import { Route as Dashboard_layoutProjectsProjectIdSettingsRouteImport } from './routes/_dashboard_layout/projects/$projectId/settings'
import { Route as Dashboard_layoutProjectsProjectIdPluginsRouteImport } from './routes/_dashboard_layout/projects/$projectId/plugins'
import { Route as Dashboard_layoutProjectsProjectIdCacheRouteImport } from './routes/_dashboard_layout/projects/$projectId/cache'
import { Route as Dashboard_layoutProjectsProjectIdAuditLogsRouteImport } from './routes/_dashboard_layout/projects/$projectId/audit-logs'
import { Route as Dashboard_layoutProjectsProjectIdAiAnalysesRouteImport } from './routes/_dashboard_layout/projects/$projectId/ai-analyses'
import { Route as Dashboard_layoutPluginsPublishersPublisherRouteImport } from './routes/_dashboard_layout/plugins/publishers/$publisher'
import { Route as Dashboard_layoutProjectsProjectIdSettingsIndexRouteImport } from './routes/_dashboard_layout/projects/$projectId/settings/index'
import { Route as Dashboard_layoutPluginsPublisherNameIndexRouteImport } from './routes/_dashboard_layout/plugins/$publisher/$name/index'
import { Route as Dashboard_layoutProjectsProjectIdSettingsGitRouteImport } from './routes/_dashboard_layout/projects/$projectId/settings/git'
import { Route as Dashboard_layoutProjectsProjectIdSettingsApiKeysRouteImport } from './routes/_dashboard_layout/projects/$projectId/settings/api-keys'
import { Route as Dashboard_layoutProjectsProjectIdRunsRunIdRouteImport } from './routes/_dashboard_layout/projects/$projectId/runs/$runId'
import { Route as Dashboard_layoutPluginsPublisherNameAnalyticsRouteImport } from './routes/_dashboard_layout/plugins/$publisher/$name/analytics'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard_layoutRoute = Dashboard_layoutRouteImport.update({
  id: '/_dashboard_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/auth/device',
  path: '/auth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard_layoutSettingsRoute =
  Dashboard_layoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutLicenseRoute = Dashboard_layoutLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => Dashboard_layoutRoute,
} as any)
const Dashboard_layoutDashboardRoute =
  Dashboard_layoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutAnalyticsRoute =
  Dashboard_layoutAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutTeamsIndexRoute =
  Dashboard_layoutTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsIndexRoute =
  Dashboard_layoutProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutInvitationsIndexRoute =
  Dashboard_layoutInvitationsIndexRouteImport.update({
    id: '/invitations/',
    path: '/invitations/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutClustersIndexRoute =
  Dashboard_layoutClustersIndexRouteImport.update({
    id: '/clusters/',
    path: '/clusters/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutPluginsIndexRoute =
  Dashboard_layoutPluginsIndexRouteImport.update({
    id: '/plugins/',
    path: '/plugins/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutPluginsPublishersIndexRoute =
  Dashboard_layoutPluginsPublishersIndexRouteImport.update({
    id: '/plugins/publishers/',
    path: '/plugins/publishers/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutWorkersIndexRoute =
  Dashboard_layoutWorkersIndexRouteImport.update({
    id: '/workers/',
    path: '/workers/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsNewIndexRoute =
  Dashboard_layoutProjectsNewIndexRouteImport.update({
    id: '/projects/new/',
    path: '/projects/new/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdRunsIndexRoute =
  Dashboard_layoutProjectsProjectIdRunsIndexRouteImport.update({
    id: '/projects/$projectId/runs/',
    path: '/projects/$projectId/runs/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const AuthProviderCallbackRoute = AuthProviderCallbackRouteImport.update({
  id: '/auth/$provider/callback',
  path: '/auth/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard_layoutWorkersWorkerIdRoute =
  Dashboard_layoutWorkersWorkerIdRouteImport.update({
    id: '/workers/$workerId',
    path: '/workers/$workerId',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutPluginsPublishRoute =
  Dashboard_layoutPluginsPublishRouteImport.update({
    id: '/plugins/publish',
    path: '/plugins/publish',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutPluginsBrowseRoute =
  Dashboard_layoutPluginsBrowseRouteImport.update({
    id: '/plugins/browse',
    path: '/plugins/browse',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutPluginsPluginNameRoute =
  Dashboard_layoutPluginsPluginNameRouteImport.update({
    id: '/plugins/$pluginName',
    path: '/plugins/$pluginName',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutClustersClusterIdRoute =
  Dashboard_layoutClustersClusterIdRouteImport.update({
    id: '/clusters/$clusterId',
    path: '/clusters/$clusterId',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutTeamsTeamIdIndexRoute =
  Dashboard_layoutTeamsTeamIdIndexRouteImport.update({
    id: '/teams/$teamId/',
    path: '/teams/$teamId/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdIndexRoute =
  Dashboard_layoutProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutTeamsTeamIdSsoRoute =
  Dashboard_layoutTeamsTeamIdSsoRouteImport.update({
    id: '/teams/$teamId/sso',
    path: '/teams/$teamId/sso',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutTeamsTeamIdAnalyticsRoute =
  Dashboard_layoutTeamsTeamIdAnalyticsRouteImport.update({
    id: '/teams/$teamId/analytics',
    path: '/teams/$teamId/analytics',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsNewGithubRoute =
  Dashboard_layoutProjectsNewGithubRouteImport.update({
    id: '/projects/new/github',
    path: '/projects/new/github',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdSettingsRoute =
  Dashboard_layoutProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdPluginsRoute =
  Dashboard_layoutProjectsProjectIdPluginsRouteImport.update({
    id: '/projects/$projectId/plugins',
    path: '/projects/$projectId/plugins',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdCacheRoute =
  Dashboard_layoutProjectsProjectIdCacheRouteImport.update({
    id: '/projects/$projectId/cache',
    path: '/projects/$projectId/cache',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdAuditLogsRoute =
  Dashboard_layoutProjectsProjectIdAuditLogsRouteImport.update({
    id: '/projects/$projectId/audit-logs',
    path: '/projects/$projectId/audit-logs',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdAiAnalysesRoute =
  Dashboard_layoutProjectsProjectIdAiAnalysesRouteImport.update({
    id: '/projects/$projectId/ai-analyses',
    path: '/projects/$projectId/ai-analyses',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutPluginsPublishersPublisherRoute =
  Dashboard_layoutPluginsPublishersPublisherRouteImport.update({
    id: '/plugins/publishers/$publisher',
    path: '/plugins/publishers/$publisher',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdSettingsIndexRoute =
  Dashboard_layoutProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Dashboard_layoutProjectsProjectIdSettingsRoute,
  } as any)
const Dashboard_layoutPluginsPublisherNameIndexRoute =
  Dashboard_layoutPluginsPublisherNameIndexRouteImport.update({
    id: '/plugins/$publisher/$name/',
    path: '/plugins/$publisher/$name/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdSettingsGitRoute =
  Dashboard_layoutProjectsProjectIdSettingsGitRouteImport.update({
    id: '/git',
    path: '/git',
    getParentRoute: () => Dashboard_layoutProjectsProjectIdSettingsRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdSettingsApiKeysRoute =
  Dashboard_layoutProjectsProjectIdSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => Dashboard_layoutProjectsProjectIdSettingsRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdRunsRunIdRoute =
  Dashboard_layoutProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/projects/$projectId/runs/$runId',
    path: '/projects/$projectId/runs/$runId',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutPluginsPublisherNameAnalyticsRoute =
  Dashboard_layoutPluginsPublisherNameAnalyticsRouteImport.update({
    id: '/plugins/$publisher/$name/analytics',
    path: '/plugins/$publisher/$name/analytics',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/analytics': typeof Dashboard_layoutAnalyticsRoute
  '/dashboard': typeof Dashboard_layoutDashboardRoute
  '/license': typeof Dashboard_layoutLicenseRoute
  '/settings': typeof Dashboard_layoutSettingsRoute
  '/auth/device': typeof AuthDeviceRoute
  '/docs/$': typeof DocsSplatRoute
  '/clusters/$clusterId': typeof Dashboard_layoutClustersClusterIdRoute
  '/plugins/$pluginName': typeof Dashboard_layoutPluginsPluginNameRoute
  '/plugins/browse': typeof Dashboard_layoutPluginsBrowseRoute
  '/plugins/publish': typeof Dashboard_layoutPluginsPublishRoute
  '/workers/$workerId': typeof Dashboard_layoutWorkersWorkerIdRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/clusters/': typeof Dashboard_layoutClustersIndexRoute
  '/invitations/': typeof Dashboard_layoutInvitationsIndexRoute
  '/plugins/': typeof Dashboard_layoutPluginsIndexRoute
  '/plugins/publishers/': typeof Dashboard_layoutPluginsPublishersIndexRoute
  '/projects/': typeof Dashboard_layoutProjectsIndexRoute
  '/projects/new/': typeof Dashboard_layoutProjectsNewIndexRoute
  '/teams/': typeof Dashboard_layoutTeamsIndexRoute
  '/workers/': typeof Dashboard_layoutWorkersIndexRoute
  '/projects/$projectId/runs/': typeof Dashboard_layoutProjectsProjectIdRunsIndexRoute
  '/plugins/publishers/$publisher': typeof Dashboard_layoutPluginsPublishersPublisherRoute
  '/projects/$projectId/ai-analyses': typeof Dashboard_layoutProjectsProjectIdAiAnalysesRoute
  '/projects/$projectId/audit-logs': typeof Dashboard_layoutProjectsProjectIdAuditLogsRoute
  '/projects/$projectId/cache': typeof Dashboard_layoutProjectsProjectIdCacheRoute
  '/projects/$projectId/plugins': typeof Dashboard_layoutProjectsProjectIdPluginsRoute
  '/projects/$projectId/settings': typeof Dashboard_layoutProjectsProjectIdSettingsRouteWithChildren
  '/projects/new/github': typeof Dashboard_layoutProjectsNewGithubRoute
  '/teams/$teamId/analytics': typeof Dashboard_layoutTeamsTeamIdAnalyticsRoute
  '/teams/$teamId/sso': typeof Dashboard_layoutTeamsTeamIdSsoRoute
  '/projects/$projectId/': typeof Dashboard_layoutProjectsProjectIdIndexRoute
  '/teams/$teamId/': typeof Dashboard_layoutTeamsTeamIdIndexRoute
  '/plugins/$publisher/$name/analytics': typeof Dashboard_layoutPluginsPublisherNameAnalyticsRoute
  '/projects/$projectId/runs/$runId': typeof Dashboard_layoutProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/settings/api-keys': typeof Dashboard_layoutProjectsProjectIdSettingsApiKeysRoute
  '/projects/$projectId/settings/git': typeof Dashboard_layoutProjectsProjectIdSettingsGitRoute
  '/plugins/$publisher/$name/': typeof Dashboard_layoutPluginsPublisherNameIndexRoute
  '/projects/$projectId/settings/': typeof Dashboard_layoutProjectsProjectIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/analytics': typeof Dashboard_layoutAnalyticsRoute
  '/dashboard': typeof Dashboard_layoutDashboardRoute
  '/license': typeof Dashboard_layoutLicenseRoute
  '/settings': typeof Dashboard_layoutSettingsRoute
  '/auth/device': typeof AuthDeviceRoute
  '/docs/$': typeof DocsSplatRoute
  '/clusters/$clusterId': typeof Dashboard_layoutClustersClusterIdRoute
  '/plugins/$pluginName': typeof Dashboard_layoutPluginsPluginNameRoute
  '/plugins/browse': typeof Dashboard_layoutPluginsBrowseRoute
  '/plugins/publish': typeof Dashboard_layoutPluginsPublishRoute
  '/workers/$workerId': typeof Dashboard_layoutWorkersWorkerIdRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/clusters': typeof Dashboard_layoutClustersIndexRoute
  '/invitations': typeof Dashboard_layoutInvitationsIndexRoute
  '/plugins': typeof Dashboard_layoutPluginsIndexRoute
  '/plugins/publishers': typeof Dashboard_layoutPluginsPublishersIndexRoute
  '/projects': typeof Dashboard_layoutProjectsIndexRoute
  '/projects/new': typeof Dashboard_layoutProjectsNewIndexRoute
  '/teams': typeof Dashboard_layoutTeamsIndexRoute
  '/workers': typeof Dashboard_layoutWorkersIndexRoute
  '/projects/$projectId/runs': typeof Dashboard_layoutProjectsProjectIdRunsIndexRoute
  '/plugins/publishers/$publisher': typeof Dashboard_layoutPluginsPublishersPublisherRoute
  '/projects/$projectId/ai-analyses': typeof Dashboard_layoutProjectsProjectIdAiAnalysesRoute
  '/projects/$projectId/audit-logs': typeof Dashboard_layoutProjectsProjectIdAuditLogsRoute
  '/projects/$projectId/cache': typeof Dashboard_layoutProjectsProjectIdCacheRoute
  '/projects/$projectId/plugins': typeof Dashboard_layoutProjectsProjectIdPluginsRoute
  '/projects/new/github': typeof Dashboard_layoutProjectsNewGithubRoute
  '/teams/$teamId/analytics': typeof Dashboard_layoutTeamsTeamIdAnalyticsRoute
  '/teams/$teamId/sso': typeof Dashboard_layoutTeamsTeamIdSsoRoute
  '/projects/$projectId': typeof Dashboard_layoutProjectsProjectIdIndexRoute
  '/teams/$teamId': typeof Dashboard_layoutTeamsTeamIdIndexRoute
  '/plugins/$publisher/$name/analytics': typeof Dashboard_layoutPluginsPublisherNameAnalyticsRoute
  '/projects/$projectId/runs/$runId': typeof Dashboard_layoutProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/settings/api-keys': typeof Dashboard_layoutProjectsProjectIdSettingsApiKeysRoute
  '/projects/$projectId/settings/git': typeof Dashboard_layoutProjectsProjectIdSettingsGitRoute
  '/plugins/$publisher/$name': typeof Dashboard_layoutPluginsPublisherNameIndexRoute
  '/projects/$projectId/settings': typeof Dashboard_layoutProjectsProjectIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard_layout': typeof Dashboard_layoutRouteWithChildren
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_dashboard_layout/analytics': typeof Dashboard_layoutAnalyticsRoute
  '/_dashboard_layout/dashboard': typeof Dashboard_layoutDashboardRoute
  '/_dashboard_layout/license': typeof Dashboard_layoutLicenseRoute
  '/_dashboard_layout/settings': typeof Dashboard_layoutSettingsRoute
  '/auth/device': typeof AuthDeviceRoute
  '/docs/$': typeof DocsSplatRoute
  '/_dashboard_layout/clusters/$clusterId': typeof Dashboard_layoutClustersClusterIdRoute
  '/_dashboard_layout/plugins/$pluginName': typeof Dashboard_layoutPluginsPluginNameRoute
  '/_dashboard_layout/plugins/browse': typeof Dashboard_layoutPluginsBrowseRoute
  '/_dashboard_layout/plugins/publish': typeof Dashboard_layoutPluginsPublishRoute
  '/_dashboard_layout/workers/$workerId': typeof Dashboard_layoutWorkersWorkerIdRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/_dashboard_layout/clusters/': typeof Dashboard_layoutClustersIndexRoute
  '/_dashboard_layout/invitations/': typeof Dashboard_layoutInvitationsIndexRoute
  '/_dashboard_layout/plugins/': typeof Dashboard_layoutPluginsIndexRoute
  '/_dashboard_layout/plugins/publishers/': typeof Dashboard_layoutPluginsPublishersIndexRoute
  '/_dashboard_layout/projects/': typeof Dashboard_layoutProjectsIndexRoute
  '/_dashboard_layout/projects/new/': typeof Dashboard_layoutProjectsNewIndexRoute
  '/_dashboard_layout/teams/': typeof Dashboard_layoutTeamsIndexRoute
  '/_dashboard_layout/workers/': typeof Dashboard_layoutWorkersIndexRoute
  '/_dashboard_layout/projects/$projectId/runs/': typeof Dashboard_layoutProjectsProjectIdRunsIndexRoute
  '/_dashboard_layout/plugins/publishers/$publisher': typeof Dashboard_layoutPluginsPublishersPublisherRoute
  '/_dashboard_layout/projects/$projectId/ai-analyses': typeof Dashboard_layoutProjectsProjectIdAiAnalysesRoute
  '/_dashboard_layout/projects/$projectId/audit-logs': typeof Dashboard_layoutProjectsProjectIdAuditLogsRoute
  '/_dashboard_layout/projects/$projectId/cache': typeof Dashboard_layoutProjectsProjectIdCacheRoute
  '/_dashboard_layout/projects/$projectId/plugins': typeof Dashboard_layoutProjectsProjectIdPluginsRoute
  '/_dashboard_layout/projects/$projectId/settings': typeof Dashboard_layoutProjectsProjectIdSettingsRouteWithChildren
  '/_dashboard_layout/projects/new/github': typeof Dashboard_layoutProjectsNewGithubRoute
  '/_dashboard_layout/teams/$teamId/analytics': typeof Dashboard_layoutTeamsTeamIdAnalyticsRoute
  '/_dashboard_layout/teams/$teamId/sso': typeof Dashboard_layoutTeamsTeamIdSsoRoute
  '/_dashboard_layout/projects/$projectId/': typeof Dashboard_layoutProjectsProjectIdIndexRoute
  '/_dashboard_layout/teams/$teamId/': typeof Dashboard_layoutTeamsTeamIdIndexRoute
  '/_dashboard_layout/plugins/$publisher/$name/analytics': typeof Dashboard_layoutPluginsPublisherNameAnalyticsRoute
  '/_dashboard_layout/projects/$projectId/runs/$runId': typeof Dashboard_layoutProjectsProjectIdRunsRunIdRoute
  '/_dashboard_layout/projects/$projectId/settings/api-keys': typeof Dashboard_layoutProjectsProjectIdSettingsApiKeysRoute
  '/_dashboard_layout/projects/$projectId/settings/git': typeof Dashboard_layoutProjectsProjectIdSettingsGitRoute
  '/_dashboard_layout/plugins/$publisher/$name/': typeof Dashboard_layoutPluginsPublisherNameIndexRoute
  '/_dashboard_layout/projects/$projectId/settings/': typeof Dashboard_layoutProjectsProjectIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sso-callback'
    | '/analytics'
    | '/dashboard'
    | '/license'
    | '/settings'
    | '/auth/device'
    | '/docs/$'
    | '/clusters/$clusterId'
    | '/plugins/$pluginName'
    | '/plugins/browse'
    | '/plugins/publish'
    | '/workers/$workerId'
    | '/auth/$provider/callback'
    | '/clusters/'
    | '/invitations/'
    | '/plugins/'
    | '/plugins/publishers/'
    | '/projects/'
    | '/projects/new/'
    | '/teams/'
    | '/workers/'
    | '/projects/$projectId/runs/'
    | '/plugins/publishers/$publisher'
    | '/projects/$projectId/ai-analyses'
    | '/projects/$projectId/audit-logs'
    | '/projects/$projectId/cache'
    | '/projects/$projectId/plugins'
    | '/projects/$projectId/settings'
    | '/projects/new/github'
    | '/teams/$teamId/analytics'
    | '/teams/$teamId/sso'
    | '/projects/$projectId/'
    | '/teams/$teamId/'
    | '/plugins/$publisher/$name/analytics'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/settings/api-keys'
    | '/projects/$projectId/settings/git'
    | '/plugins/$publisher/$name/'
    | '/projects/$projectId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sso-callback'
    | '/analytics'
    | '/dashboard'
    | '/license'
    | '/settings'
    | '/auth/device'
    | '/docs/$'
    | '/clusters/$clusterId'
    | '/plugins/$pluginName'
    | '/plugins/browse'
    | '/plugins/publish'
    | '/workers/$workerId'
    | '/auth/$provider/callback'
    | '/clusters'
    | '/invitations'
    | '/plugins'
    | '/plugins/publishers'
    | '/projects'
    | '/projects/new'
    | '/teams'
    | '/workers'
    | '/projects/$projectId/runs'
    | '/plugins/publishers/$publisher'
    | '/projects/$projectId/ai-analyses'
    | '/projects/$projectId/audit-logs'
    | '/projects/$projectId/cache'
    | '/projects/$projectId/plugins'
    | '/projects/new/github'
    | '/teams/$teamId/analytics'
    | '/teams/$teamId/sso'
    | '/projects/$projectId'
    | '/teams/$teamId'
    | '/plugins/$publisher/$name/analytics'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/settings/api-keys'
    | '/projects/$projectId/settings/git'
    | '/plugins/$publisher/$name'
    | '/projects/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/_dashboard_layout'
    | '/login'
    | '/sso-callback'
    | '/_dashboard_layout/analytics'
    | '/_dashboard_layout/dashboard'
    | '/_dashboard_layout/license'
    | '/_dashboard_layout/settings'
    | '/auth/device'
    | '/docs/$'
    | '/_dashboard_layout/clusters/$clusterId'
    | '/_dashboard_layout/plugins/$pluginName'
    | '/_dashboard_layout/plugins/browse'
    | '/_dashboard_layout/plugins/publish'
    | '/_dashboard_layout/workers/$workerId'
    | '/auth/$provider/callback'
    | '/_dashboard_layout/clusters/'
    | '/_dashboard_layout/invitations/'
    | '/_dashboard_layout/plugins/'
    | '/_dashboard_layout/plugins/publishers/'
    | '/_dashboard_layout/projects/'
    | '/_dashboard_layout/projects/new/'
    | '/_dashboard_layout/teams/'
    | '/_dashboard_layout/workers/'
    | '/_dashboard_layout/projects/$projectId/runs/'
    | '/_dashboard_layout/plugins/publishers/$publisher'
    | '/_dashboard_layout/projects/$projectId/ai-analyses'
    | '/_dashboard_layout/projects/$projectId/audit-logs'
    | '/_dashboard_layout/projects/$projectId/cache'
    | '/_dashboard_layout/projects/$projectId/plugins'
    | '/_dashboard_layout/projects/$projectId/settings'
    | '/_dashboard_layout/projects/new/github'
    | '/_dashboard_layout/teams/$teamId/analytics'
    | '/_dashboard_layout/teams/$teamId/sso'
    | '/_dashboard_layout/projects/$projectId/'
    | '/_dashboard_layout/teams/$teamId/'
    | '/_dashboard_layout/plugins/$publisher/$name/analytics'
    | '/_dashboard_layout/projects/$projectId/runs/$runId'
    | '/_dashboard_layout/projects/$projectId/settings/api-keys'
    | '/_dashboard_layout/projects/$projectId/settings/git'
    | '/_dashboard_layout/plugins/$publisher/$name/'
    | '/_dashboard_layout/projects/$projectId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Dashboard_layoutRoute: typeof Dashboard_layoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  AuthDeviceRoute: typeof AuthDeviceRoute
  DocsSplatRoute: typeof DocsSplatRoute
  AuthProviderCallbackRoute: typeof AuthProviderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard_layout': {
      id: '/_dashboard_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Dashboard_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/device': {
      id: '/auth/device'
      path: '/auth/device'
      fullPath: '/auth/device'
      preLoaderRoute: typeof AuthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard_layout/settings': {
      id: '/_dashboard_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof Dashboard_layoutSettingsRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/license': {
      id: '/_dashboard_layout/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof Dashboard_layoutLicenseRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/dashboard': {
      id: '/_dashboard_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof Dashboard_layoutDashboardRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/analytics': {
      id: '/_dashboard_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof Dashboard_layoutAnalyticsRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/teams/': {
      id: '/_dashboard_layout/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof Dashboard_layoutTeamsIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/': {
      id: '/_dashboard_layout/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof Dashboard_layoutProjectsIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/invitations/': {
      id: '/_dashboard_layout/invitations/'
      path: '/invitations'
      fullPath: '/invitations/'
      preLoaderRoute: typeof Dashboard_layoutInvitationsIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/clusters/': {
      id: '/_dashboard_layout/clusters/'
      path: '/clusters'
      fullPath: '/clusters/'
      preLoaderRoute: typeof Dashboard_layoutClustersIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/plugins/': {
      id: '/_dashboard_layout/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof Dashboard_layoutPluginsIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/plugins/publishers/': {
      id: '/_dashboard_layout/plugins/publishers/'
      path: '/plugins/publishers'
      fullPath: '/plugins/publishers/'
      preLoaderRoute: typeof Dashboard_layoutPluginsPublishersIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/workers/': {
      id: '/_dashboard_layout/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof Dashboard_layoutWorkersIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/new/': {
      id: '/_dashboard_layout/projects/new/'
      path: '/projects/new'
      fullPath: '/projects/new/'
      preLoaderRoute: typeof Dashboard_layoutProjectsNewIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/runs/': {
      id: '/_dashboard_layout/projects/$projectId/runs/'
      path: '/projects/$projectId/runs'
      fullPath: '/projects/$projectId/runs/'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdRunsIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/auth/$provider/callback': {
      id: '/auth/$provider/callback'
      path: '/auth/$provider/callback'
      fullPath: '/auth/$provider/callback'
      preLoaderRoute: typeof AuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard_layout/workers/$workerId': {
      id: '/_dashboard_layout/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof Dashboard_layoutWorkersWorkerIdRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/plugins/publish': {
      id: '/_dashboard_layout/plugins/publish'
      path: '/plugins/publish'
      fullPath: '/plugins/publish'
      preLoaderRoute: typeof Dashboard_layoutPluginsPublishRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/plugins/browse': {
      id: '/_dashboard_layout/plugins/browse'
      path: '/plugins/browse'
      fullPath: '/plugins/browse'
      preLoaderRoute: typeof Dashboard_layoutPluginsBrowseRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/plugins/$pluginName': {
      id: '/_dashboard_layout/plugins/$pluginName'
      path: '/plugins/$pluginName'
      fullPath: '/plugins/$pluginName'
      preLoaderRoute: typeof Dashboard_layoutPluginsPluginNameRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/clusters/$clusterId': {
      id: '/_dashboard_layout/clusters/$clusterId'
      path: '/clusters/$clusterId'
      fullPath: '/clusters/$clusterId'
      preLoaderRoute: typeof Dashboard_layoutClustersClusterIdRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/teams/$teamId/': {
      id: '/_dashboard_layout/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof Dashboard_layoutTeamsTeamIdIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/': {
      id: '/_dashboard_layout/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/teams/$teamId/sso': {
      id: '/_dashboard_layout/teams/$teamId/sso'
      path: '/teams/$teamId/sso'
      fullPath: '/teams/$teamId/sso'
      preLoaderRoute: typeof Dashboard_layoutTeamsTeamIdSsoRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/teams/$teamId/analytics': {
      id: '/_dashboard_layout/teams/$teamId/analytics'
      path: '/teams/$teamId/analytics'
      fullPath: '/teams/$teamId/analytics'
      preLoaderRoute: typeof Dashboard_layoutTeamsTeamIdAnalyticsRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/new/github': {
      id: '/_dashboard_layout/projects/new/github'
      path: '/projects/new/github'
      fullPath: '/projects/new/github'
      preLoaderRoute: typeof Dashboard_layoutProjectsNewGithubRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/settings': {
      id: '/_dashboard_layout/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdSettingsRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/plugins': {
      id: '/_dashboard_layout/projects/$projectId/plugins'
      path: '/projects/$projectId/plugins'
      fullPath: '/projects/$projectId/plugins'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdPluginsRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/cache': {
      id: '/_dashboard_layout/projects/$projectId/cache'
      path: '/projects/$projectId/cache'
      fullPath: '/projects/$projectId/cache'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdCacheRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/audit-logs': {
      id: '/_dashboard_layout/projects/$projectId/audit-logs'
      path: '/projects/$projectId/audit-logs'
      fullPath: '/projects/$projectId/audit-logs'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdAuditLogsRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/ai-analyses': {
      id: '/_dashboard_layout/projects/$projectId/ai-analyses'
      path: '/projects/$projectId/ai-analyses'
      fullPath: '/projects/$projectId/ai-analyses'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdAiAnalysesRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/plugins/publishers/$publisher': {
      id: '/_dashboard_layout/plugins/publishers/$publisher'
      path: '/plugins/publishers/$publisher'
      fullPath: '/plugins/publishers/$publisher'
      preLoaderRoute: typeof Dashboard_layoutPluginsPublishersPublisherRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/settings/': {
      id: '/_dashboard_layout/projects/$projectId/settings/'
      path: '/'
      fullPath: '/projects/$projectId/settings/'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof Dashboard_layoutProjectsProjectIdSettingsRoute
    }
    '/_dashboard_layout/plugins/$publisher/$name/': {
      id: '/_dashboard_layout/plugins/$publisher/$name/'
      path: '/plugins/$publisher/$name'
      fullPath: '/plugins/$publisher/$name/'
      preLoaderRoute: typeof Dashboard_layoutPluginsPublisherNameIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/settings/git': {
      id: '/_dashboard_layout/projects/$projectId/settings/git'
      path: '/git'
      fullPath: '/projects/$projectId/settings/git'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdSettingsGitRouteImport
      parentRoute: typeof Dashboard_layoutProjectsProjectIdSettingsRoute
    }
    '/_dashboard_layout/projects/$projectId/settings/api-keys': {
      id: '/_dashboard_layout/projects/$projectId/settings/api-keys'
      path: '/api-keys'
      fullPath: '/projects/$projectId/settings/api-keys'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdSettingsApiKeysRouteImport
      parentRoute: typeof Dashboard_layoutProjectsProjectIdSettingsRoute
    }
    '/_dashboard_layout/projects/$projectId/runs/$runId': {
      id: '/_dashboard_layout/projects/$projectId/runs/$runId'
      path: '/projects/$projectId/runs/$runId'
      fullPath: '/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/plugins/$publisher/$name/analytics': {
      id: '/_dashboard_layout/plugins/$publisher/$name/analytics'
      path: '/plugins/$publisher/$name/analytics'
      fullPath: '/plugins/$publisher/$name/analytics'
      preLoaderRoute: typeof Dashboard_layoutPluginsPublisherNameAnalyticsRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
  }
}

interface Dashboard_layoutProjectsProjectIdSettingsRouteChildren {
  Dashboard_layoutProjectsProjectIdSettingsApiKeysRoute: typeof Dashboard_layoutProjectsProjectIdSettingsApiKeysRoute
  Dashboard_layoutProjectsProjectIdSettingsGitRoute: typeof Dashboard_layoutProjectsProjectIdSettingsGitRoute
  Dashboard_layoutProjectsProjectIdSettingsIndexRoute: typeof Dashboard_layoutProjectsProjectIdSettingsIndexRoute
}

const Dashboard_layoutProjectsProjectIdSettingsRouteChildren: Dashboard_layoutProjectsProjectIdSettingsRouteChildren =
  {
    Dashboard_layoutProjectsProjectIdSettingsApiKeysRoute:
      Dashboard_layoutProjectsProjectIdSettingsApiKeysRoute,
    Dashboard_layoutProjectsProjectIdSettingsGitRoute:
      Dashboard_layoutProjectsProjectIdSettingsGitRoute,
    Dashboard_layoutProjectsProjectIdSettingsIndexRoute:
      Dashboard_layoutProjectsProjectIdSettingsIndexRoute,
  }

const Dashboard_layoutProjectsProjectIdSettingsRouteWithChildren =
  Dashboard_layoutProjectsProjectIdSettingsRoute._addFileChildren(
    Dashboard_layoutProjectsProjectIdSettingsRouteChildren,
  )

interface Dashboard_layoutRouteChildren {
  Dashboard_layoutAnalyticsRoute: typeof Dashboard_layoutAnalyticsRoute
  Dashboard_layoutDashboardRoute: typeof Dashboard_layoutDashboardRoute
  Dashboard_layoutLicenseRoute: typeof Dashboard_layoutLicenseRoute
  Dashboard_layoutSettingsRoute: typeof Dashboard_layoutSettingsRoute
  Dashboard_layoutClustersClusterIdRoute: typeof Dashboard_layoutClustersClusterIdRoute
  Dashboard_layoutPluginsPluginNameRoute: typeof Dashboard_layoutPluginsPluginNameRoute
  Dashboard_layoutPluginsBrowseRoute: typeof Dashboard_layoutPluginsBrowseRoute
  Dashboard_layoutPluginsPublishRoute: typeof Dashboard_layoutPluginsPublishRoute
  Dashboard_layoutWorkersWorkerIdRoute: typeof Dashboard_layoutWorkersWorkerIdRoute
  Dashboard_layoutClustersIndexRoute: typeof Dashboard_layoutClustersIndexRoute
  Dashboard_layoutInvitationsIndexRoute: typeof Dashboard_layoutInvitationsIndexRoute
  Dashboard_layoutPluginsIndexRoute: typeof Dashboard_layoutPluginsIndexRoute
  Dashboard_layoutPluginsPublishersIndexRoute: typeof Dashboard_layoutPluginsPublishersIndexRoute
  Dashboard_layoutProjectsIndexRoute: typeof Dashboard_layoutProjectsIndexRoute
  Dashboard_layoutProjectsNewIndexRoute: typeof Dashboard_layoutProjectsNewIndexRoute
  Dashboard_layoutTeamsIndexRoute: typeof Dashboard_layoutTeamsIndexRoute
  Dashboard_layoutWorkersIndexRoute: typeof Dashboard_layoutWorkersIndexRoute
  Dashboard_layoutProjectsProjectIdRunsIndexRoute: typeof Dashboard_layoutProjectsProjectIdRunsIndexRoute
  Dashboard_layoutPluginsPublishersPublisherRoute: typeof Dashboard_layoutPluginsPublishersPublisherRoute
  Dashboard_layoutProjectsProjectIdAiAnalysesRoute: typeof Dashboard_layoutProjectsProjectIdAiAnalysesRoute
  Dashboard_layoutProjectsProjectIdAuditLogsRoute: typeof Dashboard_layoutProjectsProjectIdAuditLogsRoute
  Dashboard_layoutProjectsProjectIdCacheRoute: typeof Dashboard_layoutProjectsProjectIdCacheRoute
  Dashboard_layoutProjectsProjectIdPluginsRoute: typeof Dashboard_layoutProjectsProjectIdPluginsRoute
  Dashboard_layoutProjectsProjectIdSettingsRoute: typeof Dashboard_layoutProjectsProjectIdSettingsRouteWithChildren
  Dashboard_layoutProjectsNewGithubRoute: typeof Dashboard_layoutProjectsNewGithubRoute
  Dashboard_layoutTeamsTeamIdAnalyticsRoute: typeof Dashboard_layoutTeamsTeamIdAnalyticsRoute
  Dashboard_layoutTeamsTeamIdSsoRoute: typeof Dashboard_layoutTeamsTeamIdSsoRoute
  Dashboard_layoutProjectsProjectIdIndexRoute: typeof Dashboard_layoutProjectsProjectIdIndexRoute
  Dashboard_layoutTeamsTeamIdIndexRoute: typeof Dashboard_layoutTeamsTeamIdIndexRoute
  Dashboard_layoutPluginsPublisherNameAnalyticsRoute: typeof Dashboard_layoutPluginsPublisherNameAnalyticsRoute
  Dashboard_layoutProjectsProjectIdRunsRunIdRoute: typeof Dashboard_layoutProjectsProjectIdRunsRunIdRoute
  Dashboard_layoutPluginsPublisherNameIndexRoute: typeof Dashboard_layoutPluginsPublisherNameIndexRoute
}

const Dashboard_layoutRouteChildren: Dashboard_layoutRouteChildren = {
  Dashboard_layoutAnalyticsRoute: Dashboard_layoutAnalyticsRoute,
  Dashboard_layoutDashboardRoute: Dashboard_layoutDashboardRoute,
  Dashboard_layoutLicenseRoute: Dashboard_layoutLicenseRoute,
  Dashboard_layoutSettingsRoute: Dashboard_layoutSettingsRoute,
  Dashboard_layoutClustersClusterIdRoute:
    Dashboard_layoutClustersClusterIdRoute,
  Dashboard_layoutPluginsPluginNameRoute:
    Dashboard_layoutPluginsPluginNameRoute,
  Dashboard_layoutPluginsBrowseRoute: Dashboard_layoutPluginsBrowseRoute,
  Dashboard_layoutPluginsPublishRoute: Dashboard_layoutPluginsPublishRoute,
  Dashboard_layoutWorkersWorkerIdRoute: Dashboard_layoutWorkersWorkerIdRoute,
  Dashboard_layoutClustersIndexRoute: Dashboard_layoutClustersIndexRoute,
  Dashboard_layoutInvitationsIndexRoute: Dashboard_layoutInvitationsIndexRoute,
  Dashboard_layoutPluginsIndexRoute: Dashboard_layoutPluginsIndexRoute,
  Dashboard_layoutPluginsPublishersIndexRoute: Dashboard_layoutPluginsPublishersIndexRoute,
  Dashboard_layoutProjectsIndexRoute: Dashboard_layoutProjectsIndexRoute,
  Dashboard_layoutProjectsNewIndexRoute: Dashboard_layoutProjectsNewIndexRoute,
  Dashboard_layoutTeamsIndexRoute: Dashboard_layoutTeamsIndexRoute,
  Dashboard_layoutWorkersIndexRoute: Dashboard_layoutWorkersIndexRoute,
  Dashboard_layoutProjectsProjectIdRunsIndexRoute: Dashboard_layoutProjectsProjectIdRunsIndexRoute,
  Dashboard_layoutPluginsPublishersPublisherRoute:
    Dashboard_layoutPluginsPublishersPublisherRoute,
  Dashboard_layoutProjectsProjectIdAiAnalysesRoute:
    Dashboard_layoutProjectsProjectIdAiAnalysesRoute,
  Dashboard_layoutProjectsProjectIdAuditLogsRoute:
    Dashboard_layoutProjectsProjectIdAuditLogsRoute,
  Dashboard_layoutProjectsProjectIdCacheRoute:
    Dashboard_layoutProjectsProjectIdCacheRoute,
  Dashboard_layoutProjectsProjectIdPluginsRoute:
    Dashboard_layoutProjectsProjectIdPluginsRoute,
  Dashboard_layoutProjectsProjectIdSettingsRoute:
    Dashboard_layoutProjectsProjectIdSettingsRouteWithChildren,
  Dashboard_layoutProjectsNewGithubRoute:
    Dashboard_layoutProjectsNewGithubRoute,
  Dashboard_layoutTeamsTeamIdAnalyticsRoute:
    Dashboard_layoutTeamsTeamIdAnalyticsRoute,
  Dashboard_layoutTeamsTeamIdSsoRoute: Dashboard_layoutTeamsTeamIdSsoRoute,
  Dashboard_layoutProjectsProjectIdIndexRoute:
    Dashboard_layoutProjectsProjectIdIndexRoute,
  Dashboard_layoutTeamsTeamIdIndexRoute: Dashboard_layoutTeamsTeamIdIndexRoute,
  Dashboard_layoutPluginsPublisherNameAnalyticsRoute:
    Dashboard_layoutPluginsPublisherNameAnalyticsRoute,
  Dashboard_layoutProjectsProjectIdRunsRunIdRoute:
    Dashboard_layoutProjectsProjectIdRunsRunIdRoute,
  Dashboard_layoutPluginsPublisherNameIndexRoute:
    Dashboard_layoutPluginsPublisherNameIndexRoute,
}

const Dashboard_layoutRouteWithChildren =
  Dashboard_layoutRoute._addFileChildren(Dashboard_layoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Dashboard_layoutRoute: Dashboard_layoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  AuthDeviceRoute: AuthDeviceRoute,
  DocsSplatRoute: DocsSplatRoute,
  AuthProviderCallbackRoute: AuthProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
