/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Dashboard_layoutRouteImport } from './routes/_dashboard_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDeviceRouteImport } from './routes/auth/device'
import { Route as Dashboard_layoutSettingsRouteImport } from './routes/_dashboard_layout/settings'
import { Route as Dashboard_layoutLicenseRouteImport } from './routes/_dashboard_layout/license'
import { Route as Dashboard_layoutDashboardRouteImport } from './routes/_dashboard_layout/dashboard'
import { Route as Dashboard_layoutTeamsIndexRouteImport } from './routes/_dashboard_layout/teams/index'
import { Route as Dashboard_layoutProjectsIndexRouteImport } from './routes/_dashboard_layout/projects/index'
import { Route as Dashboard_layoutInvitationsIndexRouteImport } from './routes/_dashboard_layout/invitations/index'
import { Route as AuthProviderCallbackRouteImport } from './routes/auth/$provider/callback'
import { Route as Dashboard_layoutPluginsPublishRouteImport } from './routes/_dashboard_layout/plugins/publish'
import { Route as Dashboard_layoutPluginsBrowseRouteImport } from './routes/_dashboard_layout/plugins/browse'
import { Route as Dashboard_layoutPluginsPluginNameRouteImport } from './routes/_dashboard_layout/plugins/$pluginName'
import { Route as Dashboard_layoutTeamsTeamIdIndexRouteImport } from './routes/_dashboard_layout/teams/$teamId/index'
import { Route as Dashboard_layoutProjectsProjectIdIndexRouteImport } from './routes/_dashboard_layout/projects/$projectId/index'
import { Route as Dashboard_layoutProjectsNewGithubRouteImport } from './routes/_dashboard_layout/projects/new/github'
import { Route as Dashboard_layoutProjectsProjectIdSettingsRouteImport } from './routes/_dashboard_layout/projects/$projectId/settings'
import { Route as Dashboard_layoutProjectsProjectIdPluginsRouteImport } from './routes/_dashboard_layout/projects/$projectId/plugins'
import { Route as Dashboard_layoutProjectsProjectIdCacheRouteImport } from './routes/_dashboard_layout/projects/$projectId/cache'
import { Route as Dashboard_layoutProjectsProjectIdAiAnalysesRouteImport } from './routes/_dashboard_layout/projects/$projectId/ai-analyses'
import { Route as Dashboard_layoutPluginsPublishersPublisherRouteImport } from './routes/_dashboard_layout/plugins/publishers/$publisher'
import { Route as Dashboard_layoutPluginsPublisherNameIndexRouteImport } from './routes/_dashboard_layout/plugins/$publisher/$name/index'
import { Route as Dashboard_layoutProjectsProjectIdRunsRunIdRouteImport } from './routes/_dashboard_layout/projects/$projectId/runs/$runId'
import { Route as Dashboard_layoutPluginsPublisherNameAnalyticsRouteImport } from './routes/_dashboard_layout/plugins/$publisher/$name/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard_layoutRoute = Dashboard_layoutRouteImport.update({
  id: '/_dashboard_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/auth/device',
  path: '/auth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard_layoutSettingsRoute =
  Dashboard_layoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutLicenseRoute = Dashboard_layoutLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => Dashboard_layoutRoute,
} as any)
const Dashboard_layoutDashboardRoute =
  Dashboard_layoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutTeamsIndexRoute =
  Dashboard_layoutTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsIndexRoute =
  Dashboard_layoutProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutInvitationsIndexRoute =
  Dashboard_layoutInvitationsIndexRouteImport.update({
    id: '/invitations/',
    path: '/invitations/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const AuthProviderCallbackRoute = AuthProviderCallbackRouteImport.update({
  id: '/auth/$provider/callback',
  path: '/auth/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard_layoutPluginsPublishRoute =
  Dashboard_layoutPluginsPublishRouteImport.update({
    id: '/plugins/publish',
    path: '/plugins/publish',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutPluginsBrowseRoute =
  Dashboard_layoutPluginsBrowseRouteImport.update({
    id: '/plugins/browse',
    path: '/plugins/browse',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutPluginsPluginNameRoute =
  Dashboard_layoutPluginsPluginNameRouteImport.update({
    id: '/plugins/$pluginName',
    path: '/plugins/$pluginName',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutTeamsTeamIdIndexRoute =
  Dashboard_layoutTeamsTeamIdIndexRouteImport.update({
    id: '/teams/$teamId/',
    path: '/teams/$teamId/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdIndexRoute =
  Dashboard_layoutProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsNewGithubRoute =
  Dashboard_layoutProjectsNewGithubRouteImport.update({
    id: '/projects/new/github',
    path: '/projects/new/github',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdSettingsRoute =
  Dashboard_layoutProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdPluginsRoute =
  Dashboard_layoutProjectsProjectIdPluginsRouteImport.update({
    id: '/projects/$projectId/plugins',
    path: '/projects/$projectId/plugins',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdCacheRoute =
  Dashboard_layoutProjectsProjectIdCacheRouteImport.update({
    id: '/projects/$projectId/cache',
    path: '/projects/$projectId/cache',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdAiAnalysesRoute =
  Dashboard_layoutProjectsProjectIdAiAnalysesRouteImport.update({
    id: '/projects/$projectId/ai-analyses',
    path: '/projects/$projectId/ai-analyses',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutPluginsPublishersPublisherRoute =
  Dashboard_layoutPluginsPublishersPublisherRouteImport.update({
    id: '/plugins/publishers/$publisher',
    path: '/plugins/publishers/$publisher',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutPluginsPublisherNameIndexRoute =
  Dashboard_layoutPluginsPublisherNameIndexRouteImport.update({
    id: '/plugins/$publisher/$name/',
    path: '/plugins/$publisher/$name/',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutProjectsProjectIdRunsRunIdRoute =
  Dashboard_layoutProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/projects/$projectId/runs/$runId',
    path: '/projects/$projectId/runs/$runId',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutPluginsPublisherNameAnalyticsRoute =
  Dashboard_layoutPluginsPublisherNameAnalyticsRouteImport.update({
    id: '/plugins/$publisher/$name/analytics',
    path: '/plugins/$publisher/$name/analytics',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof Dashboard_layoutDashboardRoute
  '/license': typeof Dashboard_layoutLicenseRoute
  '/settings': typeof Dashboard_layoutSettingsRoute
  '/auth/device': typeof AuthDeviceRoute
  '/plugins/$pluginName': typeof Dashboard_layoutPluginsPluginNameRoute
  '/plugins/browse': typeof Dashboard_layoutPluginsBrowseRoute
  '/plugins/publish': typeof Dashboard_layoutPluginsPublishRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/invitations/': typeof Dashboard_layoutInvitationsIndexRoute
  '/projects/': typeof Dashboard_layoutProjectsIndexRoute
  '/teams/': typeof Dashboard_layoutTeamsIndexRoute
  '/plugins/publishers/$publisher': typeof Dashboard_layoutPluginsPublishersPublisherRoute
  '/projects/$projectId/ai-analyses': typeof Dashboard_layoutProjectsProjectIdAiAnalysesRoute
  '/projects/$projectId/cache': typeof Dashboard_layoutProjectsProjectIdCacheRoute
  '/projects/$projectId/plugins': typeof Dashboard_layoutProjectsProjectIdPluginsRoute
  '/projects/$projectId/settings': typeof Dashboard_layoutProjectsProjectIdSettingsRoute
  '/projects/new/github': typeof Dashboard_layoutProjectsNewGithubRoute
  '/projects/$projectId/': typeof Dashboard_layoutProjectsProjectIdIndexRoute
  '/teams/$teamId/': typeof Dashboard_layoutTeamsTeamIdIndexRoute
  '/plugins/$publisher/$name/analytics': typeof Dashboard_layoutPluginsPublisherNameAnalyticsRoute
  '/projects/$projectId/runs/$runId': typeof Dashboard_layoutProjectsProjectIdRunsRunIdRoute
  '/plugins/$publisher/$name/': typeof Dashboard_layoutPluginsPublisherNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof Dashboard_layoutDashboardRoute
  '/license': typeof Dashboard_layoutLicenseRoute
  '/settings': typeof Dashboard_layoutSettingsRoute
  '/auth/device': typeof AuthDeviceRoute
  '/plugins/$pluginName': typeof Dashboard_layoutPluginsPluginNameRoute
  '/plugins/browse': typeof Dashboard_layoutPluginsBrowseRoute
  '/plugins/publish': typeof Dashboard_layoutPluginsPublishRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/invitations': typeof Dashboard_layoutInvitationsIndexRoute
  '/projects': typeof Dashboard_layoutProjectsIndexRoute
  '/teams': typeof Dashboard_layoutTeamsIndexRoute
  '/plugins/publishers/$publisher': typeof Dashboard_layoutPluginsPublishersPublisherRoute
  '/projects/$projectId/ai-analyses': typeof Dashboard_layoutProjectsProjectIdAiAnalysesRoute
  '/projects/$projectId/cache': typeof Dashboard_layoutProjectsProjectIdCacheRoute
  '/projects/$projectId/plugins': typeof Dashboard_layoutProjectsProjectIdPluginsRoute
  '/projects/$projectId/settings': typeof Dashboard_layoutProjectsProjectIdSettingsRoute
  '/projects/new/github': typeof Dashboard_layoutProjectsNewGithubRoute
  '/projects/$projectId': typeof Dashboard_layoutProjectsProjectIdIndexRoute
  '/teams/$teamId': typeof Dashboard_layoutTeamsTeamIdIndexRoute
  '/plugins/$publisher/$name/analytics': typeof Dashboard_layoutPluginsPublisherNameAnalyticsRoute
  '/projects/$projectId/runs/$runId': typeof Dashboard_layoutProjectsProjectIdRunsRunIdRoute
  '/plugins/$publisher/$name': typeof Dashboard_layoutPluginsPublisherNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard_layout': typeof Dashboard_layoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard_layout/dashboard': typeof Dashboard_layoutDashboardRoute
  '/_dashboard_layout/license': typeof Dashboard_layoutLicenseRoute
  '/_dashboard_layout/settings': typeof Dashboard_layoutSettingsRoute
  '/auth/device': typeof AuthDeviceRoute
  '/_dashboard_layout/plugins/$pluginName': typeof Dashboard_layoutPluginsPluginNameRoute
  '/_dashboard_layout/plugins/browse': typeof Dashboard_layoutPluginsBrowseRoute
  '/_dashboard_layout/plugins/publish': typeof Dashboard_layoutPluginsPublishRoute
  '/auth/$provider/callback': typeof AuthProviderCallbackRoute
  '/_dashboard_layout/invitations/': typeof Dashboard_layoutInvitationsIndexRoute
  '/_dashboard_layout/projects/': typeof Dashboard_layoutProjectsIndexRoute
  '/_dashboard_layout/teams/': typeof Dashboard_layoutTeamsIndexRoute
  '/_dashboard_layout/plugins/publishers/$publisher': typeof Dashboard_layoutPluginsPublishersPublisherRoute
  '/_dashboard_layout/projects/$projectId/ai-analyses': typeof Dashboard_layoutProjectsProjectIdAiAnalysesRoute
  '/_dashboard_layout/projects/$projectId/cache': typeof Dashboard_layoutProjectsProjectIdCacheRoute
  '/_dashboard_layout/projects/$projectId/plugins': typeof Dashboard_layoutProjectsProjectIdPluginsRoute
  '/_dashboard_layout/projects/$projectId/settings': typeof Dashboard_layoutProjectsProjectIdSettingsRoute
  '/_dashboard_layout/projects/new/github': typeof Dashboard_layoutProjectsNewGithubRoute
  '/_dashboard_layout/projects/$projectId/': typeof Dashboard_layoutProjectsProjectIdIndexRoute
  '/_dashboard_layout/teams/$teamId/': typeof Dashboard_layoutTeamsTeamIdIndexRoute
  '/_dashboard_layout/plugins/$publisher/$name/analytics': typeof Dashboard_layoutPluginsPublisherNameAnalyticsRoute
  '/_dashboard_layout/projects/$projectId/runs/$runId': typeof Dashboard_layoutProjectsProjectIdRunsRunIdRoute
  '/_dashboard_layout/plugins/$publisher/$name/': typeof Dashboard_layoutPluginsPublisherNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/license'
    | '/settings'
    | '/auth/device'
    | '/plugins/$pluginName'
    | '/plugins/browse'
    | '/plugins/publish'
    | '/auth/$provider/callback'
    | '/invitations/'
    | '/projects/'
    | '/teams/'
    | '/plugins/publishers/$publisher'
    | '/projects/$projectId/ai-analyses'
    | '/projects/$projectId/cache'
    | '/projects/$projectId/plugins'
    | '/projects/$projectId/settings'
    | '/projects/new/github'
    | '/projects/$projectId/'
    | '/teams/$teamId/'
    | '/plugins/$publisher/$name/analytics'
    | '/projects/$projectId/runs/$runId'
    | '/plugins/$publisher/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/license'
    | '/settings'
    | '/auth/device'
    | '/plugins/$pluginName'
    | '/plugins/browse'
    | '/plugins/publish'
    | '/auth/$provider/callback'
    | '/invitations'
    | '/projects'
    | '/teams'
    | '/plugins/publishers/$publisher'
    | '/projects/$projectId/ai-analyses'
    | '/projects/$projectId/cache'
    | '/projects/$projectId/plugins'
    | '/projects/$projectId/settings'
    | '/projects/new/github'
    | '/projects/$projectId'
    | '/teams/$teamId'
    | '/plugins/$publisher/$name/analytics'
    | '/projects/$projectId/runs/$runId'
    | '/plugins/$publisher/$name'
  id:
    | '__root__'
    | '/'
    | '/_dashboard_layout'
    | '/login'
    | '/_dashboard_layout/dashboard'
    | '/_dashboard_layout/license'
    | '/_dashboard_layout/settings'
    | '/auth/device'
    | '/_dashboard_layout/plugins/$pluginName'
    | '/_dashboard_layout/plugins/browse'
    | '/_dashboard_layout/plugins/publish'
    | '/auth/$provider/callback'
    | '/_dashboard_layout/invitations/'
    | '/_dashboard_layout/projects/'
    | '/_dashboard_layout/teams/'
    | '/_dashboard_layout/plugins/publishers/$publisher'
    | '/_dashboard_layout/projects/$projectId/ai-analyses'
    | '/_dashboard_layout/projects/$projectId/cache'
    | '/_dashboard_layout/projects/$projectId/plugins'
    | '/_dashboard_layout/projects/$projectId/settings'
    | '/_dashboard_layout/projects/new/github'
    | '/_dashboard_layout/projects/$projectId/'
    | '/_dashboard_layout/teams/$teamId/'
    | '/_dashboard_layout/plugins/$publisher/$name/analytics'
    | '/_dashboard_layout/projects/$projectId/runs/$runId'
    | '/_dashboard_layout/plugins/$publisher/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Dashboard_layoutRoute: typeof Dashboard_layoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthDeviceRoute: typeof AuthDeviceRoute
  AuthProviderCallbackRoute: typeof AuthProviderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard_layout': {
      id: '/_dashboard_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Dashboard_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/device': {
      id: '/auth/device'
      path: '/auth/device'
      fullPath: '/auth/device'
      preLoaderRoute: typeof AuthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard_layout/settings': {
      id: '/_dashboard_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof Dashboard_layoutSettingsRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/license': {
      id: '/_dashboard_layout/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof Dashboard_layoutLicenseRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/dashboard': {
      id: '/_dashboard_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof Dashboard_layoutDashboardRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/teams/': {
      id: '/_dashboard_layout/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof Dashboard_layoutTeamsIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/': {
      id: '/_dashboard_layout/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof Dashboard_layoutProjectsIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/invitations/': {
      id: '/_dashboard_layout/invitations/'
      path: '/invitations'
      fullPath: '/invitations/'
      preLoaderRoute: typeof Dashboard_layoutInvitationsIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/auth/$provider/callback': {
      id: '/auth/$provider/callback'
      path: '/auth/$provider/callback'
      fullPath: '/auth/$provider/callback'
      preLoaderRoute: typeof AuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard_layout/plugins/publish': {
      id: '/_dashboard_layout/plugins/publish'
      path: '/plugins/publish'
      fullPath: '/plugins/publish'
      preLoaderRoute: typeof Dashboard_layoutPluginsPublishRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/plugins/browse': {
      id: '/_dashboard_layout/plugins/browse'
      path: '/plugins/browse'
      fullPath: '/plugins/browse'
      preLoaderRoute: typeof Dashboard_layoutPluginsBrowseRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/plugins/$pluginName': {
      id: '/_dashboard_layout/plugins/$pluginName'
      path: '/plugins/$pluginName'
      fullPath: '/plugins/$pluginName'
      preLoaderRoute: typeof Dashboard_layoutPluginsPluginNameRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/teams/$teamId/': {
      id: '/_dashboard_layout/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof Dashboard_layoutTeamsTeamIdIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/': {
      id: '/_dashboard_layout/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/new/github': {
      id: '/_dashboard_layout/projects/new/github'
      path: '/projects/new/github'
      fullPath: '/projects/new/github'
      preLoaderRoute: typeof Dashboard_layoutProjectsNewGithubRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/settings': {
      id: '/_dashboard_layout/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdSettingsRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/plugins': {
      id: '/_dashboard_layout/projects/$projectId/plugins'
      path: '/projects/$projectId/plugins'
      fullPath: '/projects/$projectId/plugins'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdPluginsRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/cache': {
      id: '/_dashboard_layout/projects/$projectId/cache'
      path: '/projects/$projectId/cache'
      fullPath: '/projects/$projectId/cache'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdCacheRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/ai-analyses': {
      id: '/_dashboard_layout/projects/$projectId/ai-analyses'
      path: '/projects/$projectId/ai-analyses'
      fullPath: '/projects/$projectId/ai-analyses'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdAiAnalysesRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/plugins/publishers/$publisher': {
      id: '/_dashboard_layout/plugins/publishers/$publisher'
      path: '/plugins/publishers/$publisher'
      fullPath: '/plugins/publishers/$publisher'
      preLoaderRoute: typeof Dashboard_layoutPluginsPublishersPublisherRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/plugins/$publisher/$name/': {
      id: '/_dashboard_layout/plugins/$publisher/$name/'
      path: '/plugins/$publisher/$name'
      fullPath: '/plugins/$publisher/$name/'
      preLoaderRoute: typeof Dashboard_layoutPluginsPublisherNameIndexRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/projects/$projectId/runs/$runId': {
      id: '/_dashboard_layout/projects/$projectId/runs/$runId'
      path: '/projects/$projectId/runs/$runId'
      fullPath: '/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof Dashboard_layoutProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/_dashboard_layout/plugins/$publisher/$name/analytics': {
      id: '/_dashboard_layout/plugins/$publisher/$name/analytics'
      path: '/plugins/$publisher/$name/analytics'
      fullPath: '/plugins/$publisher/$name/analytics'
      preLoaderRoute: typeof Dashboard_layoutPluginsPublisherNameAnalyticsRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
  }
}

interface Dashboard_layoutRouteChildren {
  Dashboard_layoutDashboardRoute: typeof Dashboard_layoutDashboardRoute
  Dashboard_layoutLicenseRoute: typeof Dashboard_layoutLicenseRoute
  Dashboard_layoutSettingsRoute: typeof Dashboard_layoutSettingsRoute
  Dashboard_layoutPluginsPluginNameRoute: typeof Dashboard_layoutPluginsPluginNameRoute
  Dashboard_layoutPluginsBrowseRoute: typeof Dashboard_layoutPluginsBrowseRoute
  Dashboard_layoutPluginsPublishRoute: typeof Dashboard_layoutPluginsPublishRoute
  Dashboard_layoutInvitationsIndexRoute: typeof Dashboard_layoutInvitationsIndexRoute
  Dashboard_layoutProjectsIndexRoute: typeof Dashboard_layoutProjectsIndexRoute
  Dashboard_layoutTeamsIndexRoute: typeof Dashboard_layoutTeamsIndexRoute
  Dashboard_layoutPluginsPublishersPublisherRoute: typeof Dashboard_layoutPluginsPublishersPublisherRoute
  Dashboard_layoutProjectsProjectIdAiAnalysesRoute: typeof Dashboard_layoutProjectsProjectIdAiAnalysesRoute
  Dashboard_layoutProjectsProjectIdCacheRoute: typeof Dashboard_layoutProjectsProjectIdCacheRoute
  Dashboard_layoutProjectsProjectIdPluginsRoute: typeof Dashboard_layoutProjectsProjectIdPluginsRoute
  Dashboard_layoutProjectsProjectIdSettingsRoute: typeof Dashboard_layoutProjectsProjectIdSettingsRoute
  Dashboard_layoutProjectsNewGithubRoute: typeof Dashboard_layoutProjectsNewGithubRoute
  Dashboard_layoutProjectsProjectIdIndexRoute: typeof Dashboard_layoutProjectsProjectIdIndexRoute
  Dashboard_layoutTeamsTeamIdIndexRoute: typeof Dashboard_layoutTeamsTeamIdIndexRoute
  Dashboard_layoutPluginsPublisherNameAnalyticsRoute: typeof Dashboard_layoutPluginsPublisherNameAnalyticsRoute
  Dashboard_layoutProjectsProjectIdRunsRunIdRoute: typeof Dashboard_layoutProjectsProjectIdRunsRunIdRoute
  Dashboard_layoutPluginsPublisherNameIndexRoute: typeof Dashboard_layoutPluginsPublisherNameIndexRoute
}

const Dashboard_layoutRouteChildren: Dashboard_layoutRouteChildren = {
  Dashboard_layoutDashboardRoute: Dashboard_layoutDashboardRoute,
  Dashboard_layoutLicenseRoute: Dashboard_layoutLicenseRoute,
  Dashboard_layoutSettingsRoute: Dashboard_layoutSettingsRoute,
  Dashboard_layoutPluginsPluginNameRoute:
    Dashboard_layoutPluginsPluginNameRoute,
  Dashboard_layoutPluginsBrowseRoute: Dashboard_layoutPluginsBrowseRoute,
  Dashboard_layoutPluginsPublishRoute: Dashboard_layoutPluginsPublishRoute,
  Dashboard_layoutInvitationsIndexRoute: Dashboard_layoutInvitationsIndexRoute,
  Dashboard_layoutProjectsIndexRoute: Dashboard_layoutProjectsIndexRoute,
  Dashboard_layoutTeamsIndexRoute: Dashboard_layoutTeamsIndexRoute,
  Dashboard_layoutPluginsPublishersPublisherRoute:
    Dashboard_layoutPluginsPublishersPublisherRoute,
  Dashboard_layoutProjectsProjectIdAiAnalysesRoute:
    Dashboard_layoutProjectsProjectIdAiAnalysesRoute,
  Dashboard_layoutProjectsProjectIdCacheRoute:
    Dashboard_layoutProjectsProjectIdCacheRoute,
  Dashboard_layoutProjectsProjectIdPluginsRoute:
    Dashboard_layoutProjectsProjectIdPluginsRoute,
  Dashboard_layoutProjectsProjectIdSettingsRoute:
    Dashboard_layoutProjectsProjectIdSettingsRoute,
  Dashboard_layoutProjectsNewGithubRoute:
    Dashboard_layoutProjectsNewGithubRoute,
  Dashboard_layoutProjectsProjectIdIndexRoute:
    Dashboard_layoutProjectsProjectIdIndexRoute,
  Dashboard_layoutTeamsTeamIdIndexRoute: Dashboard_layoutTeamsTeamIdIndexRoute,
  Dashboard_layoutPluginsPublisherNameAnalyticsRoute:
    Dashboard_layoutPluginsPublisherNameAnalyticsRoute,
  Dashboard_layoutProjectsProjectIdRunsRunIdRoute:
    Dashboard_layoutProjectsProjectIdRunsRunIdRoute,
  Dashboard_layoutPluginsPublisherNameIndexRoute:
    Dashboard_layoutPluginsPublisherNameIndexRoute,
}

const Dashboard_layoutRouteWithChildren =
  Dashboard_layoutRoute._addFileChildren(Dashboard_layoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Dashboard_layoutRoute: Dashboard_layoutRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthDeviceRoute: AuthDeviceRoute,
  AuthProviderCallbackRoute: AuthProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
